---
name: CI

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Test
        run: go test ./... -v
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
