---
name: Create Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: write
      deployments: none
      id-token: none
      issues: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: Set up Go
        # Github Action as the label "Verified creator" https://github.com/marketplace/actions/setup-go-environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Go test
        run: go test ./... -v

      - name: Release the Go application
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
